matrix:
  include:
    - language: go
      go:
        - '1.10.x'
        - '1.11.x'
      before_script:
        - cd go
        - make install-test-deps
      script:
        - make test

    - language: node_js
      node_js:
        - '11'
      before_script:
        - cd javascript
        - make install-test-deps
      script:
        - make test

    - language: python
      include:
        - python: '3.4'
        - python: '3.5'
        - python: '3.6'
        - python: '3.7'
      before_script:
        - cd python
        - python -m pip install --upgrade pip
        - make install-test-deps PYTHON=python
      script:
        - make test PYTHON=python
    
    - language: ruby
      rvm:
        - 2.4.1
        - 2.5.3
        - 2.6.0
      before_script:
        - cd ruby
        - make install-test-deps
      script:
        - make test