matrix:
  include:
    - language: go
      go: '1.10.x'
      install:
        - go get -u -v ./go/...
      script:
        - go test -v ./go/...

    - language: go
      go: '1.11.x'
      install:
        - go get -u -v ./go/...
      script:
        - go test -v ./go/...

    - language: node_js
      node_js: '11'
      install:
        - make -C javascript install-test-deps
      script:
        - make -C javascript test

    - language: python
      python: '3.4'
      install:
        - pip install --upgrade pip
        - pip install --upgrade -r python/requirements.txt
        - pip install --upgrade -r python/requirements-test.txt
      script:
        - make -C python test PYTHON=python
    
    - language: python
      python: '3.5'
      install:
        - pip install --upgrade pip
        - pip install --upgrade -r python/requirements.txt
        - pip install --upgrade -r python/requirements-test.txt
      script:
        - make -C python test PYTHON=python
    
    - language: python
      python: '3.6'
      install:
        - pip install --upgrade pip
        - pip install --upgrade -r python/requirements.txt
        - pip install --upgrade -r python/requirements-test.txt
      script:
        - make -C python test PYTHON=python
    
    - language: python
      python: '3.7'
      dist: xenial
      install:
        - pip install --upgrade pip
        - pip install --upgrade -r python/requirements.txt
        - pip install --upgrade -r python/requirements-test.txt
      script:
        - make -C python test PYTHON=python
    
    - language: ruby
      rvm: '2.4.1'
      install:
        - make -C ruby install-test-deps
      script:
        - make -C ruby test

    - language: ruby
      rvm: '2.5.3'
      install:
        - make -C ruby install-test-deps
      script:
        - make -C ruby test

    - language: ruby
      rvm: '2.6.0'
      install:
        - make -C ruby install-test-deps
      script:
        - make -C ruby test
